# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
pool:
    vmImage: 'ubuntu-latest'
  
steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: '6801522a-f52d-48a9-b457-aee6d3eea3cf'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Create a resource group
        az group create --name JohnIaC --location 'Canada Central'
  
        # Deploy the Bicep file
        az deployment group create --resource-group JohnIaC --template-file 'appgateway.bicep'
  