trigger: 
  - main

stages:
  - stage: BGDeploy
    jobs:
      - job: Blue
        displayName: 'Deploy Blue'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure portal'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name iacimpement-blue --location 'Canada Central'

                az deployment group create --resource-group iacimplement-blue --template-file 'main.bicep'
      
      - job: Green
        displayName: 'Deploy Green'
        dependsOn: Blue
        condition: succeeded()
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure portal'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name iacimpement-green --location 'Canada Central'

                az deployment group create --resource-group iacimplement-green --template-file 'main.bicep'