trigger:
  branches:
    include:
      - main
      - blue-green

stages:
  - stage: DeployToTest
    jobs:
      - job: DeployToTestJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            clean: true
          # Additional steps for deploying to the test environment

  - stage: DeployToProd
    jobs:
      - job: DeployToProdJob
        pool:
          vmImage: 'ubuntu-latest'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/blue-green'))
        steps:
          - checkout: self
            clean: true
          # Additional steps for deploying to the production environment
