# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - blue-green
  
pool:
    vmImage: 'ubuntu-latest'
  
stages:
  - stage: deploytest
    displayName: 'Deploy to Test'
    jobs:
      - job: bgtest
        displayName: 'Deployment to Test'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'iacimplement-test'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name iacimplement-test --location 'Canada Central'

                az deployment group create --resource-group iacimplement-test --template-file 'main.bicep'


  - stage: deployprod
    displayName: 'Deploy to Production'
    condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/blue-green'))
    jobs:
      - deployment: deploytoprodjob
        displayName: 'Deploy to Production'
        environment: 'iacimplement-prod'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    git checkout blue-green
                    ls -la

                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'iacimplement-prod'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az group create --name iacimplement-prod --location 'Canada Central'

                      az deployment group create --resource-group iacimplement-prod --template-file 'main.bicep'
                    
                      