# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
stages:
  - stage: blueDeploy
    jobs:
      - job: deployBlue
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az group create --name iacimplement --location 'Canada Central'

              az deployment group create --resource-group iacimplement --template-file 'main.bicep'
            displayName: 'Deploy Blue Environment'